require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project 'project_base',
    'Debug' => :debug,
    'Release' => :release,
    'DevelopDebug' => :debug,
    'DevelopRelease' => :release,
    'StagingDebug' => :debug,
    'StagingRelease' => :release,
    'ProductionDebug' => :debug,
    'ProductionRelease' => :release

platform :ios, '10.0'

target 'project_base' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false # current Realm 10.6.1 does not support hermes
  )

  target 'project_baseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
    react_native_post_install(installer)
  end
end
################# my add #################
#Fix: Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
#I would recommend following Plasma's answer. However, if you don't want to delete the master repo, just mute the warning by adding the warn_for_unused_master_specs_repo setting to your Podfile by changing this:
#If you already have an option after install! 'cocoapods', append the new setting with a comma:
#install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

